spring:
  #postgresql db 설정
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://#url#
    username: #username#
    password: #password#
    hikari:
      connection-timeout: 3000
      validation-timeout: 3000
      minimum-idle: 5 # 연결 풀에서 hikaricp 가 유지 관리하는 최소 유휴 연결 수
      max-lifetime: 240000 # 닫힌 후 pool 에 있는 connection의 최대 수명 (ms)
      maximum-pool-size: 20 # 최대 pool 사이즈
  mail:
    host: smtp.gmail.com
    port: 587
    username: #이메일 주소#
    password: #이메일 전송 패스워드#
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 180000  # 3 * 60 * 1000 == 3분

  data:
    redis:
      pool:
        max-active: 5
        max-idle: 5
        min-idle: 2
      host: #hostname#
      port: #port#
      password: #redis_password#

# mybatis 설정
mybatis:
  type-aliases-package: com.ysl.calendar
  mapper-locations: classpath:mapper/*.xml

# logging
logging:
  level:
    org.hibernate.SQL: info
    root: error
    com.zaxxer.hikari.pool.HikariPool: debug
    com.ysl.calendar: debug
